//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroCalendar.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetroCalendar.Resources.Localizations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutAppbarText {
            get {
                return ResourceManager.GetString("AboutAppbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metro Calendar for Windows Phone 7
        ///Version 01.00.00
        ///Copyright © 2011-2012 by Panda Work Studio.
        /// </summary>
        public static string AboutContentText {
            get {
                return ResourceManager.GetString("AboutContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alarm.
        /// </summary>
        public static string AlarmAppbarText {
            get {
                return ResourceManager.GetString("AlarmAppbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm ends earlier than it starts..
        /// </summary>
        public static string AlarmExpirationWarningText {
            get {
                return ResourceManager.GetString("AlarmExpirationWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm time has passed, please reset it!.
        /// </summary>
        public static string AlarmExpiredWarningText {
            get {
                return ResourceManager.GetString("AlarmExpiredWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        public static string AlarmHeadText {
            get {
                return ResourceManager.GetString("AlarmHeadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm time.
        /// </summary>
        public static string AlarmTimeHeadText {
            get {
                return ResourceManager.GetString("AlarmTimeHeadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anniversary.
        /// </summary>
        public static string AnniversaryAppbarText {
            get {
                return ResourceManager.GetString("AnniversaryAppbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anniversary ends earlier than it starts..
        /// </summary>
        public static string AnniversaryExpirationWarningText {
            get {
                return ResourceManager.GetString("AnniversaryExpirationWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anniversary.
        /// </summary>
        public static string AnniversaryText {
            get {
                return ResourceManager.GetString("AnniversaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string AprText {
            get {
                return ResourceManager.GetString("AprText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string AugText {
            get {
                return ResourceManager.GetString("AugText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beijing, China
        ///Designer: Sun Jinbo
        ///Email: sunjinbo@hotmail.com.
        /// </summary>
        public static string AuthorContentText {
            get {
                return ResourceManager.GetString("AuthorContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelAppbarText {
            get {
                return ResourceManager.GetString("CancelAppbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current day.
        /// </summary>
        public static string CurrentdayText {
            get {
                return ResourceManager.GetString("CurrentdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string DailyText {
            get {
                return ResourceManager.GetString("DailyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string DecText {
            get {
                return ResourceManager.GetString("DecText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteAppbarText {
            get {
                return ResourceManager.GetString("DeleteAppbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string DoneAppbarText {
            get {
                return ResourceManager.GetString("DoneAppbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subject cannot be empty, please fill it first..
        /// </summary>
        public static string EmptySubjectWarningText {
            get {
                return ResourceManager.GetString("EmptySubjectWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter subject.
        /// </summary>
        public static string EnterSubjectText {
            get {
                return ResourceManager.GetString("EnterSubjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration time.
        /// </summary>
        public static string ExpirationTimeHeadText {
            get {
                return ResourceManager.GetString("ExpirationTimeHeadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string FebText {
            get {
                return ResourceManager.GetString("FebText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festival.
        /// </summary>
        public static string FestivalText {
            get {
                return ResourceManager.GetString("FestivalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortnightly.
        /// </summary>
        public static string FortnightlyText {
            get {
                return ResourceManager.GetString("FortnightlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        public static string InitializingText {
            get {
                return ResourceManager.GetString("InitializingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string JanText {
            get {
                return ResourceManager.GetString("JanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string JulText {
            get {
                return ResourceManager.GetString("JulText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string JunText {
            get {
                return ResourceManager.GetString("JunText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string MarText {
            get {
                return ResourceManager.GetString("MarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string MayText {
            get {
                return ResourceManager.GetString("MayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to memo.
        /// </summary>
        public static string MemoAppbarText {
            get {
                return ResourceManager.GetString("MemoAppbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string MonthlyText {
            get {
                return ResourceManager.GetString("MonthlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next alarm.
        /// </summary>
        public static string NextAlarmText {
            get {
                return ResourceManager.GetString("NextAlarmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No alarm.
        /// </summary>
        public static string NoAlarmText {
            get {
                return ResourceManager.GetString("NoAlarmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only today.
        /// </summary>
        public static string NotRepeatedText {
            get {
                return ResourceManager.GetString("NotRepeatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string NovText {
            get {
                return ResourceManager.GetString("NovText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string OctText {
            get {
                return ResourceManager.GetString("OctText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string OkAppbarText {
            get {
                return ResourceManager.GetString("OkAppbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string PauseAppbarText {
            get {
                return ResourceManager.GetString("PauseAppbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string PauseText {
            get {
                return ResourceManager.GetString("PauseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string PlayAppbarText {
            get {
                return ResourceManager.GetString("PlayAppbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        public static string PlayingText {
            get {
                return ResourceManager.GetString("PlayingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string RecordingText {
            get {
                return ResourceManager.GetString("RecordingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (REC TIME).
        /// </summary>
        public static string RecordTimeText {
            get {
                return ResourceManager.GetString("RecordTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string RepeatHeadText {
            get {
                return ResourceManager.GetString("RepeatHeadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly repeat.
        /// </summary>
        public static string RepeatYearlyText {
            get {
                return ResourceManager.GetString("RepeatYearlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resume.
        /// </summary>
        public static string ResumeAppbarText {
            get {
                return ResourceManager.GetString("ResumeAppbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringtone.
        /// </summary>
        public static string RingtoneHeadText {
            get {
                return ResourceManager.GetString("RingtoneHeadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string SepText {
            get {
                return ResourceManager.GetString("SepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string StopAppbarText {
            get {
                return ResourceManager.GetString("StopAppbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject (limit 26 chars).
        /// </summary>
        public static string SubjectHeadText {
            get {
                return ResourceManager.GetString("SubjectHeadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string TodayText {
            get {
                return ResourceManager.GetString("TodayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        public static string UpdateAppbarText {
            get {
                return ResourceManager.GetString("UpdateAppbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrating alert.
        /// </summary>
        public static string VibratingAlertHeadText {
            get {
                return ResourceManager.GetString("VibratingAlertHeadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice memo.
        /// </summary>
        public static string VoiceMemoText {
            get {
                return ResourceManager.GetString("VoiceMemoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningTitleText {
            get {
                return ResourceManager.GetString("WarningTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        public static string WeekendText {
            get {
                return ResourceManager.GetString("WeekendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string WeeklyText {
            get {
                return ResourceManager.GetString("WeeklyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workday.
        /// </summary>
        public static string WorkdayText {
            get {
                return ResourceManager.GetString("WorkdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string YearlyText {
            get {
                return ResourceManager.GetString("YearlyText", resourceCulture);
            }
        }
    }
}
